export const environment = {
  production: false,
  enableMockAuth: true,
  authApiUrl: '/api/auth',
  requestOptionsApiUrl: '/api/request-options',
  adminDirectoryApiUrl: '/api/admin',
  staffTasksApiUrl: '/api/staff-tasks',
  eventsApiUrl: '/api/events',
  eventEngagementApiUrl: '/api/event-engagement',
  proposalWorkflowApiUrl: '/api/proposal-workflow',
  configApiUrl: '/api/config',
  eventCatalogApiUrl: '/api/event-catalog',
  cafeteriasApiUrl: '/api/cafeterias',
  imageUploadApiUrl: '/api/uploads',
  clubsApiUrl: '/api',
  useMockImageUpload: true,
} as const;
