-- ============================================================================
-- Migration 003 - make nav_page_grants.grant_id self-assigning.
--
-- DOCUMENTED DEVIATION from ems_database_schema.sql (001).
--
-- The source schema declares:
--     grant_id INTEGER PRIMARY KEY
-- with no DEFAULT and no sequence. Every other table in the schema uses
-- BIGSERIAL for its surrogate key; this one is the exception, almost certainly
-- because the JSON mock assigned ids in application code (nextId()).
--
-- Left as-is, every INSERT would have to compute max(grant_id)+1 and then race
-- any concurrent insert for the same value. The Page Visibility admin screen
-- creates these rows interactively, so that race is reachable in normal use.
--
-- Column NAME and TYPE are unchanged; only the default is added, so existing
-- rows and every query against them keep working untouched.
-- ============================================================================

ALTER TABLE nav_page_grants
    ALTER COLUMN grant_id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Start the sequence past anything already present, so an explicitly-inserted
-- id (as the seed does) cannot later collide with a generated one.
SELECT setval(
    pg_get_serial_sequence('nav_page_grants', 'grant_id'),
    GREATEST((SELECT COALESCE(max(grant_id), 0) FROM nav_page_grants), 1)
);
