import { RequestOption } from './request-option.models';

export const MOCK_REQUEST_OPTIONS: readonly RequestOption[] = [
  { id: 'log-registration-table', kind: 'logistics', label: 'Registration table', availableQuantity: 1, quantityUnit: 'table', description: 'For guest registration and check-in.', imageDataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="400" height="300" fill="%23edf2f7"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" font-family="sans-serif" font-size="20" font-weight="bold" fill="%232b6cb0">Registration Table</text></svg>', imageFileName: 'registration-table.svg', active: true },
  { id: 'log-chairs', kind: 'logistics', label: 'Chairs', availableQuantity: 200, quantityUnit: 'chair', imageDataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="400" height="300" fill="%23edf2f7"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" font-family="sans-serif" font-size="20" font-weight="bold" fill="%232b6cb0">Event Chairs</text></svg>', imageFileName: 'chairs.svg', active: true },
  { id: 'log-banquet-tables', kind: 'logistics', label: 'Banquet tables', availableQuantity: 20, quantityUnit: 'table', active: true },
  { id: 'log-directional-standees', kind: 'logistics', label: 'Directional standees', availableQuantity: 10, quantityUnit: 'standee', active: true },
  { id: 'log-stage-riser', kind: 'logistics', label: 'Stage riser', availableQuantity: 4, quantityUnit: 'section', active: true },
  { id: 'log-queue-barriers', kind: 'logistics', label: 'Queue barriers', availableQuantity: 16, quantityUnit: 'barrier', active: true },
  { id: 'transport-university-van', kind: 'transportation', label: 'University van', passengerCapacity: 10, availableVehicles: 3, imageDataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="400" height="300" fill="%23ebf8ff"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" font-family="sans-serif" font-size="20" font-weight="bold" fill="%232b6cb0">University Van</text></svg>', imageFileName: 'university-van.svg', active: true },
  { id: 'transport-chartered-bus', kind: 'transportation', label: 'Chartered bus', passengerCapacity: 44, availableVehicles: 2, imageDataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="400" height="300" fill="%23e6fffa"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" font-family="sans-serif" font-size="20" font-weight="bold" fill="%23234e52">Chartered Bus</text></svg>', imageFileName: 'chartered-bus.svg', active: true },
  { id: 'transport-grab-voucher', kind: 'transportation', label: 'Grab voucher', passengerCapacity: 4, availableVehicles: 20, description: 'Capacity is per vehicle.', active: true },
  { id: 'transport-vip-car', kind: 'transportation', label: 'VIP car', passengerCapacity: 4, availableVehicles: 2, active: true },
  { id: 'transport-airport-pickup', kind: 'transportation', label: 'Airport pickup', passengerCapacity: 6, availableVehicles: 2, active: true },
  { id: 'media-photographer', kind: 'photoVideo', label: 'Photographer', maximumPersonnel: 4, active: true },
  { id: 'media-videographer', kind: 'photoVideo', label: 'Videographer', maximumPersonnel: 4, active: true },
  { id: 'media-team', kind: 'photoVideo', label: 'Photo and video team', maximumPersonnel: 8, active: true },
  { id: 'media-livestream', kind: 'photoVideo', label: 'Livestream support', maximumPersonnel: 5, active: true },
  { id: 'av-wireless-microphone', kind: 'soundLight', label: 'Wireless microphone', availableQuantity: 12, active: true },
  { id: 'av-pa-system', kind: 'soundLight', label: 'PA system', availableQuantity: 4, active: true },
  { id: 'av-projector', kind: 'soundLight', label: 'Projector support', availableQuantity: 8, active: true },
  { id: 'av-stage-lighting', kind: 'soundLight', label: 'Stage lighting', availableQuantity: 3, active: true },
  { id: 'av-led-screen', kind: 'soundLight', label: 'LED screen', availableQuantity: 2, active: true },
  { id: 'serving-pax', kind: 'servingUnit', label: 'Per pax', description: 'One serving for one person.', active: true },
  { id: 'serving-set', kind: 'servingUnit', label: 'Per set', active: true },
  { id: 'serving-tray', kind: 'servingUnit', label: 'Per tray', active: true },
  { id: 'serving-piece', kind: 'servingUnit', label: 'Per piece', active: true },
  { id: 'serving-bottle', kind: 'servingUnit', label: 'Per bottle', active: true },
  { id: 'dietary-standard', kind: 'dietaryInformation', label: 'Standard menu', description: 'No special dietary classification.', active: true },
  { id: 'dietary-vegetarian', kind: 'dietaryInformation', label: 'Vegetarian', active: true },
  { id: 'dietary-vegan', kind: 'dietaryInformation', label: 'Vegan', active: true },
  { id: 'dietary-gluten-free', kind: 'dietaryInformation', label: 'Gluten-free', active: true },
  { id: 'dietary-allergen-aware', kind: 'dietaryInformation', label: 'Allergen-aware', description: 'Confirm the specific allergen requirements before ordering.', active: true },
  { id: 'food-lunch', kind: 'fmb', label: 'Lunch', servingUnitId: 'serving-pax', dietaryInformationId: 'dietary-standard', active: true },
  { id: 'food-dinner', kind: 'fmb', label: 'Dinner', servingUnitId: 'serving-pax', dietaryInformationId: 'dietary-standard', active: true },
  { id: 'food-refreshments', kind: 'fmb', label: 'Refreshments', servingUnitId: 'serving-pax', dietaryInformationId: 'dietary-standard', active: true },
  { id: 'food-coffee-tea', kind: 'fmb', label: 'Coffee / Tea', servingUnitId: 'serving-pax', dietaryInformationId: 'dietary-standard', active: true },
  { id: 'food-buffet', kind: 'fmb', label: 'Buffet', servingUnitId: 'serving-pax', dietaryInformationId: 'dietary-standard', active: true },
  { id: 'food-other', kind: 'fmb', label: 'Other', active: true },
  { id: 'tour-start-lobby', kind: 'campusTourStart', label: 'Main Lobby', meetingInstructions: 'Meet beside the reception desk.', maximumGroupSize: 30, active: true },
  { id: 'tour-start-atrium', kind: 'campusTourStart', label: 'Atrium', maximumGroupSize: 50, active: true },
  { id: 'tour-start-admissions', kind: 'campusTourStart', label: 'Admissions Office', maximumGroupSize: 20, active: true },
  { id: 'tour-start-library', kind: 'campusTourStart', label: 'Library Entrance', maximumGroupSize: 25, active: true },
  ...(['waterLogo', 'waterNormal'] as const).flatMap((kind) => [24, 48, 96, 120].map((count) => ({ id: `${kind}-${count}`, kind, label: `${count} bottles`, bottleCount: count, availableStock: 500, brandingRequirement: kind === 'waterLogo' ? 'APU logo artwork is required.' : undefined, active: true }))),
  { id: 'waterLogo-custom', kind: 'waterLogo', label: 'Custom quantity', bottleCount: 0, availableStock: 500, brandingRequirement: 'APU logo artwork is required.', active: true },
  { id: 'waterNormal-custom', kind: 'waterNormal', label: 'Custom quantity', bottleCount: 0, availableStock: 500, active: true },
  { id: 'fund-main-printing', kind: 'fundingMain', label: 'Printing and materials', financeCode: 'PRINT', active: true },
  { id: 'fund-main-venue', kind: 'fundingMain', label: 'Venue setup', financeCode: 'VENUE', active: true },
  { id: 'fund-main-honorarium', kind: 'fundingMain', label: 'Honorarium', financeCode: 'HON', active: true },
  { id: 'fund-main-external', kind: 'fundingMain', label: 'External service', financeCode: 'EXT', active: true },
  { id: 'fund-main-supplies', kind: 'fundingMain', label: 'Event supplies', financeCode: 'SUP', active: true },
  ...[
    ['fund-sub-posters', 'Posters and flyers', 'fund-main-printing'], ['fund-sub-certificates', 'Certificates', 'fund-main-printing'], ['fund-sub-name-tags', 'Name tags', 'fund-main-printing'], ['fund-sub-booklets', 'Programme booklets', 'fund-main-printing'],
    ['fund-sub-furniture', 'Furniture rental', 'fund-main-venue'], ['fund-sub-decorations', 'Decorations', 'fund-main-venue'], ['fund-sub-backdrop', 'Backdrop production', 'fund-main-venue'], ['fund-sub-booth', 'Booth setup', 'fund-main-venue'],
    ['fund-sub-speaker', 'Guest speaker', 'fund-main-honorarium'], ['fund-sub-facilitator', 'Facilitator', 'fund-main-honorarium'], ['fund-sub-performer', 'Performer', 'fund-main-honorarium'], ['fund-sub-judge', 'External judge', 'fund-main-honorarium'],
    ['fund-sub-security', 'Security service', 'fund-main-external'], ['fund-sub-cleaning', 'Cleaning service', 'fund-main-external'], ['fund-sub-medical', 'Medical support', 'fund-main-external'], ['fund-sub-contractor', 'Technical contractor', 'fund-main-external'],
    ['fund-sub-kits', 'Participant kits', 'fund-main-supplies'], ['fund-sub-stationery', 'Stationery', 'fund-main-supplies'], ['fund-sub-prizes', 'Prizes and tokens', 'fund-main-supplies'], ['fund-sub-consumables', 'Consumable supplies', 'fund-main-supplies'],
  ].map(([id, label, parentId]) => ({ id, kind: 'fundingSub' as const, label, parentId, active: true })),
];
