import { AuthUser, UserRole } from './auth.models';

export interface MockAuthRecord extends AuthUser { readonly password: string; }

const roleDetails: Readonly<Record<UserRole, { label: string; department: string }>> = {
  [UserRole.ExternalUser]: { label: 'Registered External User', department: 'External Community' },
  [UserRole.Applicant]: { label: 'Applicant', department: 'APU Community' },
  [UserRole.ClubPresident]: { label: 'Club President', department: 'Student Clubs and Societies' },
  [UserRole.HosHod]: { label: 'HOS / HOD', department: 'School Leadership' },
  [UserRole.Cfo]: { label: 'CFO', department: 'Finance Office' },
  [UserRole.Fmb]: { label: 'F&B', department: 'Food & Beverage Services' },
  [UserRole.CafeteriaManager]: { label: 'Cafeteria Manager', department: 'Cafeteria Services' },
  [UserRole.CafeteriaStaff]: { label: 'Cafeteria Staff', department: 'Cafeteria Services' },
  [UserRole.CafeteriaAdmin]: { label: 'Cafeteria Admin', department: 'System Administration' },
  [UserRole.LogisticsManager]: { label: 'Logistics Manager', department: 'Logistics and Facilities' },
  [UserRole.LogisticsStaff]: { label: 'Logistics Staff', department: 'Logistics and Facilities' },
  [UserRole.StudentServicesManager]: { label: 'Student Services Manager', department: 'Student Services' },
  [UserRole.StudentServicesMember]: { label: 'Student Services Member', department: 'Student Services' },
  [UserRole.AvManager]: { label: 'A/V Manager', department: 'A/V Services' },
  [UserRole.AvTechnician]: { label: 'A/V Technician', department: 'A/V Services' },
  [UserRole.PhotographyManager]: { label: 'Photography Manager', department: 'Photography Services' },
  [UserRole.PhotographyStaff]: { label: 'Photography Staff', department: 'Photography Services' },
  [UserRole.TransportManager]: { label: 'Transport Manager', department: 'Transport Services' },
  [UserRole.TransportStaff]: { label: 'Transport Driver / Staff', department: 'Transport Services' },
  [UserRole.SystemAdmin]: { label: 'System Admin', department: 'System Administration' },
};

const account = (email: string, displayName: string, role: UserRole, cafeteriaId?: number): MockAuthRecord => ({
  email,
  displayName,
  username: email.split('@', 1)[0],
  role,
  accountType: 'internal',
  roleLabel: roleDetails[role].label,
  department: roleDetails[role].department,
  password: 'Demo@123',
  ...(cafeteriaId !== undefined ? { cafeteriaId } : {}),
});

export const MOCK_AUTH_USERS: readonly MockAuthRecord[] = [
  account('applicant@demo.apu.edu.my', 'Applicant Demo', UserRole.Applicant),
  account('club.president@demo.apu.edu.my', 'Club President Demo', UserRole.ClubPresident),
  account('hoshod@demo.apu.edu.my', 'HOS / HOD Demo', UserRole.HosHod),
  account('cfo@demo.apu.edu.my', 'CFO Demo', UserRole.Cfo),
  account('fmb@demo.apu.edu.my', 'F&B Demo', UserRole.Fmb),
  account('cafeteria.manager@demo.apu.edu.my', 'Cafeteria Manager', UserRole.CafeteriaManager, 1),
  account('cafeteria.staff@demo.apu.edu.my', 'Cafeteria Staff', UserRole.CafeteriaStaff),
  account('cafeteria.admin@demo.apu.edu.my', 'Cafeteria Admin', UserRole.CafeteriaAdmin),
  account('logistics.manager@demo.apu.edu.my', 'Logistics Manager', UserRole.LogisticsManager),
  account('logistics.staff@demo.apu.edu.my', 'Ahmad (Logistics Staff)', UserRole.LogisticsStaff),
  account('logistics.staff2@demo.apu.edu.my', 'David Tan (Logistics Tech)', UserRole.LogisticsStaff),
  account('logistics.staff3@demo.apu.edu.my', 'Sarah Lee (Logistics Assistant)', UserRole.LogisticsStaff),
  account('student.services.manager@demo.apu.edu.my', 'Student Services Manager', UserRole.StudentServicesManager),
  account('student.services.member@demo.apu.edu.my', 'Priyah (Student Services Member)', UserRole.StudentServicesMember),
  account('student.services.member2@demo.apu.edu.my', 'Jason Lim (Campus Tour Guide)', UserRole.StudentServicesMember),
  account('student.services.member3@demo.apu.edu.my', 'Chloe Tan (Student Ambassador)', UserRole.StudentServicesMember),
  account('av.manager@demo.apu.edu.my', 'A/V Manager', UserRole.AvManager),
  account('av.technician@demo.apu.edu.my', 'Marcus Vance (Senior A/V Tech)', UserRole.AvTechnician),
  account('av.technician2@demo.apu.edu.my', 'Ethan Wong (Sound Engineer)', UserRole.AvTechnician),
  account('av.technician3@demo.apu.edu.my', 'Nurul Huda (Lighting Specialist)', UserRole.AvTechnician),
  account('photography.manager@demo.apu.edu.my', 'Photography Manager', UserRole.PhotographyManager),
  account('photographer@demo.apu.edu.my', 'Alex Rivera (Photographer)', UserRole.PhotographyStaff),
  account('photographer2@demo.apu.edu.my', 'Samantha Ong (Videographer)', UserRole.PhotographyStaff),
  account('transport.manager@demo.apu.edu.my', 'Transport Manager', UserRole.TransportManager),
  account('transport.staff@demo.apu.edu.my', 'Captain Bob (Transport Driver)', UserRole.TransportStaff),
  account('transport.staff2@demo.apu.edu.my', 'Harish Kumar (Fleet Coordinator)', UserRole.TransportStaff),
  account('system.admin@demo.apu.edu.my', 'System Admin', UserRole.SystemAdmin),
];
